# Generated by Django 3.2 on 2021-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('pin_code', models.IntegerField(max_length=10)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '.u_name',
            },
        ),
    ]
