# Generated by Django 3.2 on 2021-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Food Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('restaurant', models.IntegerField()),
                ('food_image', models.ImageField(upload_to='FOOD')),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
    ]
