# Generated by Django 3.1.7 on 2021-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210616_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='restaurant',
            field=models.CharField(max_length=100),
        ),
    ]
