# Generated by Django 3.1.7 on 2021-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210617_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='restaurant',
            field=models.IntegerField(),
        ),
    ]
