# Generated by Django 3.1.7 on 2021-06-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('ph_no', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
