# Generated by Django 3.1.7 on 2021-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
